### ISSUE TITLE
Correctly aligned MIDIs?

### ISSUE THREAD

**Issue by elly0t** [hexahedria/biaxial-rnn-music-composition#10]
Hi,

I have been testing the system with various collections of MIDIs, each from one renowned classical composer (e.g. Bach, Mozart...). All of the MIDIs were obtained from [www.midiworld.com](url).

Unfortunately all of the outputs appear just to be a sequence of random notes, with extremely rapid tempo. I reckon that's due to those inputs' quality. Therefore I am wondering if you can share the MIDIs you used originally for generating those amazing compositions on your website? 

Thanks in advance!

**Comment by rorokuno** [comment]
I'm not the author, but he clearly states (on his [weblog](http://www.hexahedria.com/2015/08/03/composing-music-with-recurrent-neural-networks/)) that the original source is <http://www.piano-midi.de>.

**Comment by elly0t** [comment]
Yeh I used those as well, probably because my machine isn't powerful
enough..

I was just wondering if any preprocessing was applied on those midis.

Cheers anyway!

**Comment by codekatte** [comment]
I have the same request as elly0t. It would be really helpful if you provide the original dataset you used for training. 

Thanks in advanced.

**Comment by hexahedria** [comment]
The original dataset I used was from http://www.piano-midi.de. One thing you have to be careful about is that some MIDI files are not quantized appropriately (i.e. the notes don't line up with the beat markers in the MIDI piece). The network only trains adequately if it can figure out where the beats are.
