### ISSUE TITLE
issue with 'out of memory'

### ISSUE THREAD

**Issue by burness** [hexahedria/biaxial-rnn-music-composition#15]
I have run your code with GPU but met a problem with "out of memory" like in http://deeplearning.net/software/theano/faq.html "Out of memory... but not really". Is it ok for you to use a gpu to run this code ?

**Comment by hexahedria** [comment]
Yeah, it's fine to use GPUs. But sometimes that error does happen.

Are you doing anything else on the GPU at the moment? If so, that might use up part of the GPU memory and cause there to be not enough room to train. If not, perhaps your GPU is too small to hold that many batches at once. To fix that, you can try changing the line
`allow_gc=False
`
to
`allow_gc=True
`
in your ~/.theanorc file to enable garbage collection. If that doesn't work, you can reduce the batch size [here](https://github.com/hexahedria/biaxial-rnn-music-composition/blob/master/multi_training.py#L8).
