### ISSUE TITLE
numpy.repeat TypeError on 32 bit systems

### ISSUE THREAD

**Issue by Microkitty** [hexahedria/biaxial-rnn-music-composition#20]
Traceback (most recent call last):
...
self.setup_train()
time_outputs_info = [initial_state_with_taps(layer, num_time_parallel) for layer in self.time_model.layers]
...
return matrixify(layer.initial_hidden_state, dimensions) if has_hidden(layer) else None
return T.repeat(T.shape_padleft(vector), n, axis=0)
...
TypeError: ("dtypes ('uint32', 'int64', 'uint64') are not supported by numpy.repeat for the 'repeats' parameter, ", 'int64')

**Comment by hexahedria** [comment]
Hmm... Are you running on a 32 bit OS, by any chance? It looks like there's some code in Theano that doesn't allow certain dtypes if you are using a 32 bit OS.

One possible solution would be to switch to a 64 bit OS. If that's not practical, you can try replacing that line with `T.repeat(T.shape_padleft(vector), T.cast(n,"int32"), axis=0)`, which should cast it to a useable type.

Let me know if that fixes it. If so I'll commit that change to the repo.

**Comment by Microkitty** [comment]
Exactly, I am running it in a 32-bit Python. I have tried your idea, it really works. In addition, I fix it in another way. Here is it: T.repeat(T.shape_padleft(vector), n if (theano.gof.local_bitwidth() == 64) else n.astype('int32'), axis=0). Thank you very much!
