### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MissT157** [hexahedria/biaxial-rnn-music-composition#21]
Hi I am getting the following error:
ValueError: ('The following error happened while compiling the node', forall_inplace,gpu,scan_fn}(Elemwise{switch,no_inplace}.0, Subtensor{int64:int64:int8}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, Elemwise{switch,no_inplace}.0, Layer.linear_matrix, Layer.linear_matrix, Layer.linear_matrix, Layer.linear_matrix, Layer.linear_matrix, Layer.linear_matrix, Layer.linear_matrix, Layer.linear_matrix, GpuFromHost.0, GpuFromHost.0, GpuDimShuffle{0,x}.0, GpuDimShuffle{0,x}.0, GpuDimShuffle{0,x}.0, GpuDimShuffle{0,x}.0, GpuDimShuffle{0,x}.0, GpuDimShuffle{0,x}.0, GpuDimShuffle{0,x}.0, GpuDimShuffle{0,x}.0), '\n', 'numpy.dtype has the wrong size, try recompiling')

For the following line
        self.update_fun = theano.function(
            inputs=[self.input_mat, self.output_mat],
            outputs=self.cost,
            updates=updates,
            allow_input_downcast=True)

Do you have any idea why?

**Comment by hexahedria** [comment]
That error means that your version of numpy is older than the version of numpy Theano wants. Try updating numpy to the latest version.
