### ISSUE TITLE
Allocation error

### ISSUE THREAD

**Issue by MissT157** [hexahedria/biaxial-rnn-music-composition#22]
I am getting the following error

RuntimeError: CudaNdarray_ZEROS: allocation failed.

![pic](https://cloud.githubusercontent.com/assets/6824100/21306531/740ed2be-c5f7-11e6-91b4-2232e1edf1c9.png)

is this because of theano version?

Thanks

**Comment by MissT157** [comment]
As far as I can see it, it is mainly an allocation error. Can you suggest any changes to the code in order to circumvent this issue?

**Comment by hexahedria** [comment]
Yeah, that looks like an allocation failure.

Are you doing anything else on the GPU at the moment? If so, that might use up part of the GPU memory and cause there to be not enough room to train. If not, perhaps your GPU is too small to process the default number of batches. To fix that, you can try changing the line
`allow_gc=False
`
to
`allow_gc=True
`
in your ~/.theanorc file to enable garbage collection. If that doesn't work, you can reduce the batch size [here](https://github.com/hexahedria/biaxial-rnn-music-composition/blob/master/multi_training.py#L8). You might also look at [this part of the Theano FAQ](http://deeplearning.net/software/theano/faq.html#theano-memory-speed-trade-off)
