### ISSUE TITLE
Issue with local_bitwidth()

### ISSUE THREAD

**Issue by MikhailMS** [hexahedria/biaxial-rnn-music-composition#23]
Following error occurs when running app on 64bit system
`model.py", line 21, in matrixify
    n if (theano.gof.local_bitwidth() == 64) else T.cast(n,'int32'),
AttributeError: 'module' object has no attribute 'local_bitwidth'`

However, if change code in `module.py` from
`return T.repeat(T.shape_padleft(vector),
                    n if (theano.gof.local_bitwidth() == 64) else T.cast(n,'int32'),
                    axis=0)`
back to 
`return T.repeat(T.shape_padleft(vector), n, axis=0)` 
no error occurs.

**Comment by hexahedria** [comment]
Should be fixed now.
