### ISSUE TITLE
Any way to train on CPU?

### ISSUE THREAD

**Issue by hanyucc** [hexahedria/biaxial-rnn-music-composition#29]
Is it possible to train the network on CPU instead of GPU? And how long would it possibly take?

**Comment by danieldjohnson** [comment]
You should be able to train on the CPU by changing your theano config to use `device=cpu`. I'm not sure how long that would take; it will depend on your particular computer (but probably longer than if you used a GPU).

**Comment by namratasaun** [comment]
How to do that?
