### ISSUE TITLE
model 

### ISSUE THREAD

**Issue by hugo-pires** [hexahedria/biaxial-rnn-music-composition#5]
Hello

When I try to run
m = model.Model([300,300],[100,50], dropout=0.5)

from python shell program doesn't give me any response (even error message)

Could you help me?

Thank you

**Comment by hugo-pires** [comment]
Correction: Error message

model.py:367: UserWarning: Updating an `OrderedUpdates` with a non-ordered dictionary with 2+ elements could make your code non-deterministic
  self.walk_input: next_input
model.py:370: UserWarning: Updating an `OrderedUpdates` with a non-ordered dictionary with 2+ elements could make your code non-deterministic
  updates.update({hidden:newstate for hidden, newstate, layer in zip(self.walk_hiddens, new_states, self.time_model.layers) if has_hidden(layer)})

**Comment by hexahedria** [comment]
It takes a long time for Theano to compile the model, so it doesn't show output for a while. And that warning doesn't apply in this case. If you just wait long enough, it should complete.

**Comment by sneh-d** [comment]
Facing same problem. It does not work
