### ISSUE TITLE
Failed to alloc

### ISSUE THREAD

**Issue by aquastar** [hexahedria/biaxial-rnn-music-composition#6]
I ran codes without any change, but error info as follow, could you give some suggestion:

![image](https://cloud.githubusercontent.com/assets/2832070/10777708/90bd00ea-7cf4-11e5-9dad-e2051faf3b03.png)

**Comment by ruohoruotsi** [comment]
What was the issue here, do you remember? Cheers rr

**Comment by aquastar** [comment]
change theano to 0.70, everything is gonna be perfect
